# Site settings
title: DhakadFoody | Simply Tasty
description: "blogs for food recipe with difference."
url: "http://dhakadfoody.com"
author:
  name: "Arun Gupta"
  email: "team.dhakadfoody@gmail.com"
  url: ""
# Build settings
baseurl: "" # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"
comments: true
# Options
custom_header: false
custom_nav_footer: false
reverse: false
# Build settings

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: http-dhakadfoody-com


